hosts: all
  #become: yes
  gather_facts: yes
  tasks:
  - name: Git checkout
    ping:
  - name: Download foo.conf
    get_url:
      url: 'https://nodejs.org/dist/v16.13.2/node-v16.13.2-linux-x64.tar.xz'
      dest: /opt/node.tar.xz
      mode: '0440'

  - name: Extract foo.tgz into /var/lib/foo
    ansible.builtin.unarchive:
      src: /opt/node.tar.xz
      dest: /opt
      remote_src: yes
  - name: add  to path
    lineinfile:
      dest: '/root/.profile'
      state: present
      line: 'export PATH=$PATH:/opt/node-v16.13.2-linux-x64/bin'
  - name: Unconditionally reboot the machine with all defaults
    ansible.builtin.reboot:
  - name: Nodejs version
    shell: node -v
  - name: Git checkout
    file:
      path: /opt/back-front-example
      state: directory
  - name: Git checkout
    git:
      repo: https://github.com/RoboInterativo/back-front-example
      dest: /opt/back-front-example
  - name: co
    shell: '. /root/.profile &&  cd /opt/back-front-example/front2 && npm install && npm run build'